name: collectionPostMan
on: 
  push: 
  workflow_dispatch:
jobs: 
    execute-postman-tests:    
       runs-on: ubuntu-latest
       steps:
        - name: recuperer le code
          uses: actions/checkout@v4

        - name: Install Newman
          run: npm install -g newman
      
        - name: install HTMLextra
          run: npm install -g newman-reporter-htmlextra
          

        - name: Run Postman tests
          run: newman run postman/collection.json --reporters=cli,htmlextra
        - name: Upload Test Report
          uses: actions/upload-artifact@v2
          with:
            name: postman-report
            path: report.html
